/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pengambilantiket;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static pengambilantiket.Koneksi.getConnection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author I GUSTI KOMANG AGUS PRAMANA
 * NIM: 2201010190
 * KELAS: L
 * TANGGAL 16/6/2024
 */
public class frntiket extends javax.swing.JFrame {
    DefaultTableModel tk = new DefaultTableModel();

    /**
     * Creates new form frntiket
     */
    public frntiket() throws SQLException {
        initComponents();
        jtb.setModel(tk);
        tk.addColumn("ID");
        tk.addColumn("Nama");
        tk.addColumn("Nim");
        tk.addColumn("Angkatan");
        tk.addColumn("Jumlah Tiket");
        list_all();
    }
        private void list_all() throws SQLException {
    Connection cnn = getConnection();

    tk.getDataVector().removeAllElements();
    tk.fireTableDataChanged();
    if (cnn.isClosed()) {
        System.out.println("Koneksi Gagal");
    } else {
        String sql = "SELECT * FROM datatiket ORDER BY idtiket;";
        PreparedStatement ps = cnn.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();

        while (rs.next()) {
            Object[] dta = new Object[5]; // Adjusted the size to 5
            dta[0] = rs.getInt("idtiket");
            dta[1] = rs.getString("Nama");
            dta[2] = rs.getString("Nim");
            dta[3] = rs.getString("Angkatan");
            dta[4] = rs.getString("Jumlah");
            tk.addRow(dta);
        }
        cnn.close();
    }
}

    private void StoreData() throws SQLException {
    Connection cnn = getConnection();
    String NM = bxNama.getText();
    String NI = bxNim.getText();
    String AT = bxAngkatan.getText();
    String JM = bxJumlah.getText();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("INSERT INTO datatiket(nama, nim, angkatan, jumlah) VALUES (?, ?, ?, ?)");
        ps.setString(1, NM);
        ps.setString(2, NI);
        ps.setString(3, AT);
        ps.setString(4, JM);
        ps.executeUpdate();
        cnn.close();
    }
}

private void UpdateData() throws SQLException {
    Connection cnn = getConnection();
    if (!cnn.isClosed()) {
        String idTeman = lbTiket.getText();
        String NM = bxNama.getText();
        String NI = bxNim.getText();
        String AT = bxAngkatan.getText();
        String JM = bxJumlah.getText();
        
        PreparedStatement ps = cnn.prepareStatement("UPDATE datatiket SET nama=?, nim=?, angkatan=?, jumlah=? WHERE idtiket=?;");
        ps.setString(1, NM);
        ps.setString(2, NI);
        ps.setString(3, AT);
        ps.setString(4, JM);
        ps.setString(5, idTeman);
        ps.executeUpdate();
        
        cnn.close();
    }
}

private void DestroyData() throws SQLException {
    Connection cnn = getConnection();
    if (!cnn.isClosed()) {
        PreparedStatement ps = cnn.prepareStatement("DELETE FROM datatiket WHERE idtiket=?;");
        ps.setString(1, lbTiket.getText());
        ps.executeUpdate();
        cnn.close();
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtb = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTiket = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bxNama = new javax.swing.JTextField();
        bxNim = new javax.swing.JTextField();
        bxAngkatan = new javax.swing.JTextField();
        bxJumlah = new javax.swing.JTextField();
        cmdUbah = new javax.swing.JButton();
        cmdHapus = new javax.swing.JButton();
        cmdTutup = new javax.swing.JButton();
        cmdBaru = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtb);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Daftar Pengambilan");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tiket Diesteria");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Record:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("/");

        lbTiket.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbTiket.setText("999");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("999");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nama:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Nim:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Angkatan:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Jumlah Tiket:");

        bxNama.setText(" ");
        bxNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxNamaActionPerformed(evt);
            }
        });

        bxNim.setText(" ");
        bxNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxNimActionPerformed(evt);
            }
        });

        bxAngkatan.setText(" ");
        bxAngkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxAngkatanActionPerformed(evt);
            }
        });

        bxJumlah.setText(" ");
        bxJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bxJumlahActionPerformed(evt);
            }
        });

        cmdUbah.setBackground(new java.awt.Color(255, 255, 102));
        cmdUbah.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cmdUbah.setText("Ubah");
        cmdUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdUbahActionPerformed(evt);
            }
        });

        cmdHapus.setBackground(new java.awt.Color(255, 51, 51));
        cmdHapus.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cmdHapus.setForeground(new java.awt.Color(255, 255, 255));
        cmdHapus.setText("Hapus");
        cmdHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdHapusActionPerformed(evt);
            }
        });

        cmdTutup.setBackground(new java.awt.Color(0, 0, 0));
        cmdTutup.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cmdTutup.setForeground(new java.awt.Color(255, 255, 255));
        cmdTutup.setText("Tutup");
        cmdTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdTutupActionPerformed(evt);
            }
        });

        cmdBaru.setBackground(new java.awt.Color(102, 255, 102));
        cmdBaru.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        cmdBaru.setText("Baru");
        cmdBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBaruActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(bxNim, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(bxNama, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bxAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bxJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmdTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbTiket)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(9, 9, 9)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lbTiket)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bxNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bxNim, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bxAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bxJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdTutup, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bxNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bxNamaActionPerformed

    private void bxNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bxNimActionPerformed

    private void bxAngkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxAngkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bxAngkatanActionPerformed

    private void bxJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bxJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bxJumlahActionPerformed

    private void cmdHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdHapusActionPerformed
            try {
        int jtp = JOptionPane.showOptionDialog(this, 
                "Yakin akan menghapus data " + bxNama.getText() + "?", 
                "Konfirmasi Hapus Data", 
                JOptionPane.YES_NO_OPTION, 
                JOptionPane.ERROR_MESSAGE, 
                null, 
                null, 
                null);
        if (jtp == JOptionPane.YES_OPTION) {
            DestroyData(); // Hapus data dari database
            list_all(); // Perbarui tabel
        }
    } catch (SQLException ex) {
        Logger.getLogger(frntiket.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_cmdHapusActionPerformed

    private void cmdBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBaruActionPerformed
          if (cmdBaru.getText().equals("Baru")){
            cmdBaru.setText("Simpan");
            cmdTutup.setText("Batal");
            cmdHapus.setEnabled(false);
            
            bxNama.setText("");
            bxNim.setText("");
            bxAngkatan.setText("");
            bxJumlah.setText("");
        }else{
            try {
                StoreData();
                list_all();
            } catch (SQLException ex) {
                Logger.getLogger(frntiket.class.getName()).log(Level.SEVERE, null, ex);
            }
            cmdBaru.setText("Baru");
            cmdTutup.setText("Tutup");
            cmdHapus.setEnabled(true);
        }
    }//GEN-LAST:event_cmdBaruActionPerformed

    private void cmdUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdUbahActionPerformed
        try{
           UpdateData();
           list_all();
       } catch (SQLException ex) {
           System.out.print("Terjadi Eror");
       }
    }//GEN-LAST:event_cmdUbahActionPerformed

    private void jtbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbMouseClicked
        lbTiket.setText(jtb.getValueAt(jtb.getSelectedRow(), 0).toString());
        bxNama.setText(jtb.getValueAt(jtb.getSelectedRow(), 1).toString());
        bxNim.setText(jtb.getValueAt(jtb.getSelectedRow(), 2).toString());
        bxAngkatan.setText(jtb.getValueAt(jtb.getSelectedRow(), 3).toString());
        bxJumlah.setText(jtb.getValueAt(jtb.getSelectedRow(), 4).toString());
    }//GEN-LAST:event_jtbMouseClicked

    private void cmdTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdTutupActionPerformed
                if (cmdTutup.getText().equals("Tutup")) {
    int jtp = JOptionPane.showOptionDialog(this, "Yakin akan menutup form?", "Konfirmasi Tutup Form", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    if (jtp == JOptionPane.YES_OPTION) {
        dispose();
    }
} else {
    cmdTutup.setText("Tutup");
    cmdBaru.setText("Baru");
    cmdHapus.setEnabled(true);
}
    }//GEN-LAST:event_cmdTutupActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bxAngkatan;
    private javax.swing.JTextField bxJumlah;
    private javax.swing.JTextField bxNama;
    private javax.swing.JTextField bxNim;
    private javax.swing.JButton cmdBaru;
    private javax.swing.JButton cmdHapus;
    private javax.swing.JButton cmdTutup;
    private javax.swing.JButton cmdUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtb;
    private javax.swing.JLabel lbTiket;
    // End of variables declaration//GEN-END:variables
}
